[workspace]
resolver = "2"

members = [
    "chat_diy",
    "chat1",
    "chat2",
    "chat3",
    "chat4",
    "pipe_diy",
    "pipe1",
    "pipe2",
    "pipe3",
    "pipe4",
    "iroh-chat-diy",
    "iroh-chat1",
    "iroh-chat2",
    "iroh-chat3",
]
