[workspace]
resolver = "2"

members = [
    "chat-diy",
    "chat1",
    "chat2",
    "chat3",
    "pipe-diy",
    "pipe1",
    "pipe2",
    "pipe3",
    "pipe4",
    "raw-chat-diy",
    "raw-chat1",
    "raw-chat2",
    "raw-chat3",
    "raw-chat4",
]
